const MOCK = [
  {
    id: 1,
    Name: "EchoStar Corporation",
    Type: "burger",
    Price: 23,
    image: "../images/burger2.jpg",
  },
  {
    id: 2,
    Name: "Nustar Energy L.P.",
    Type: "burger",
    Price: 41,
    image: "../images/burger1.jpg",
  },
  {
    id: 3,
    Name: "WMIH Corp.",
    Type: "burger",
    Price: 32,
    image: "../images/burger4.jpg",
  },
  {
    id: 4,
    Name: "Axsome Therapeutics, Inc.",
    Type: "burger",
    Price: 11,
    image: "../images/burger3.jpg",
  },
  {
    id: 5,
    Name: "Toll Brothers Inc.",
    Type: "pizza",
    Price: 39,
    image: "../images/pizza1.jpg",
  },
  {
    id: 6,
    Name: "Brocade Communications Systems, Inc.",
    Type: "pizza",
    Price: 19,
    image: "../images/pizza1.jpg",
  },
  {
    id: 7,
    Name: "Winmark Corporation",
    Type: "pizza",
    Price: 44,
    image: "../images/pizza1.jpg",
  },
  {
    id: 8,
    Name: "../images/pizza2.jpg",
    Type: "pizza",
    Price: 22,
    image: "../images/pizza1.jpg",
  },
  {
    id: 9,
    Name: "Tsakos Energy Navigation Ltd",
    Type: "pizza",
    Price: 87,
    image: "../images/pizza3.jpg",
  },
  {
    id: 10,
    Name: "Sajan, Inc.",
    Type: "pizza",
    Price: 85,
    image: "../images/pizza4.jpg",
  },
  {
    id: 11,
    Name: "Jagged Peak Energy Inc.",
    Type: "pizza",
    Price: 15,
    image: "../images/pizza3.jpg",
  },
  {
    id: 12,
    Name: "PowerShares LadderRite 0-5 Year Corporate Bond Portfolio",
    Type: "pizza",
    Price: 1,
    image: "../images/pizza4.jpg",
  },
  {
    id: 13,
    Name: "Landmark Infrastructure Partners LP",
    Type: "pizza",
    Price: 98,
    image: "../images/pizza1.jpg",
  },
  {
    id: 14,
    Name: "FMC Corporation",
    Type: "pizza",
    Price: 57,
    image: "../images/pizza1.jpg",
  },
  {
    id: 15,
    Name: "Hercules Capital, Inc.",
    Type: "pizza",
    Price: 73,
    image: "../images/pizza1.jpg",
  },
  {
    id: 16,
    Name: "DLH Holdings Corp.",
    Type: "pizza",
    Price: 51,
    image: "../images/pizza1.jpg",
  },
  {
    id: 17,
    Name: "Sanmina Corporation",
    Type: "pizza",
    Price: 1,
    image: "../images/pizza1.jpg",
  },
  {
    id: 18,
    Name: "Easterly Acquisition Corp.",
    Type: "pizza",
    Price: 33,
    image: "../images/pizza1.jpg",
  },
  {
    id: 19,
    Name: "Arlington Asset Investment Corp",
    Type: "pizza",
    Price: 89,
    image: "../images/pizza1.jpg",
  },
  {
    id: 20,
    Name: "Kennametal Inc.",
    Type: "pizza",
    image: "../images/pizza1.jpg",
    Price: 77,
  },
  {
    id: 21,
    Name: "CHS Inc",
    Type: "pizza",
    Price: 77,
    image: "../images/pizza1.jpg",
  },
  {
    id: 22,
    Name: "Atlas Air Worldwide Holdings",
    Type: "pizza",
    Price: 53,
    image: "../images/pizza1.jpg",
  },
  {
    id: 23,
    Name: "JMU Limited",
    Type: "pizza",
    Price: 85,
    image: "../images/pizza1.jpg",
  },
  {
    id: 24,
    Name: "First Trust NASDAQ-100- Technology Index Fund",
    Type: "pizza",
    Price: 67,
    image: "../images/pizza1.jpg",
  },
  {
    id: 25,
    Name: "Stock Yards Bancorp, Inc.",
    Type: "pizza",
    Price: 86,
    image: "../images/pizza1.jpg",
  },
  {
    id: 26,
    Name: "Dynegy Inc.",
    Type: "pizza",
    Price: 43,
    image: "../images/pizza1.jpg",
  },
  {
    id: 27,
    Name: "CSG Systems International, Inc.",
    Type: "pizza",
    Price: 93,
    image: "../images/pizza1.jpg",
  },
  {
    id: 28,
    Name: "Marinus Pharmaceuticals, Inc.",
    Type: "pizza",
    Price: 9,
    image: "../images/pizza1.jpg",
  },
  {
    id: 29,
    Name: "Atara Biotherapeutics, Inc.",
    Type: "pizza",
    Price: 96,
    image: "../images/pizza1.jpg",
  },
  {
    id: 30,
    Name: "PCM, Inc.",
    Type: "pizza",
    Price: 73,
    image: "../images/pizza1.jpg",
  },
  {
    id: 31,
    Name: "Fiat Chrysler Automobiles N.V.",
    Type: "pizza",
    Price: 96,
    image: "../images/pizza1.jpg",
  },
  {
    id: 32,
    Name: "L.S. Starrett Company (The)",
    Type: "pizza",
    Price: 74,
    image: "../images/pizza1.jpg",
  },
  {
    id: 33,
    Name: "First Trust NASDAQ Technology Dividend Index Fund",
    Type: "pizza",
    Price: 30,
    image: "../images/pizza1.jpg",
  },
  {
    id: 34,
    Name: "AmTrust Financial Services, Inc.",
    Type: "pizza",
    Price: 29,
    image: "../images/pizza1.jpg",
  },
  {
    id: 35,
    Name: "The Blackstone Group L.P.",
    Type: "pizza",
    Price: 37,
    image: "../images/pizza1.jpg",
  },
  {
    id: 36,
    Name: "Asia Pacific Fund, Inc. (The)",
    Type: "pizza",
    Price: 2,
    image: "../images/pizza1.jpg",
  },
  {
    id: 37,
    Name: "Iridium Communications Inc",
    Type: "pizza",
    Price: 61,
    image: "../images/pizza1.jpg",
  },
  {
    id: 38,
    Name: "BlackRock Income Investment Quality Trust",
    Type: "pizza",
    Price: 9,
    image: "../images/pizza1.jpg",
  },
  {
    id: 39,
    Name: "Resource Capital Corp.",
    Type: "pizza",
    Price: 89,
    image: "../images/pizza1.jpg",
  },
  {
    id: 40,
    Name: "Calumet Specialty Products Partners, L.P.",
    Type: "pizza",
    Price: 84,
    image: "../images/pizza1.jpg",
  },
  {
    id: 41,
    Name: "Gabelli Utility Trust (The)",
    Type: "pizza",
    Price: 49,
    image: "../images/pizza1.jpg",
  },
  {
    id: 42,
    Name: "Koninklijke Philips N.V.",
    Type: "pizza",
    Price: 51,
    image: "../images/pizza1.jpg",
  },
  {
    id: 43,
    Name: "Eagle Point Credit Company Inc.",
    Type: "pizza",
    Price: 48,
    image: "../images/pizza1.jpg",
  },
];

export default MOCK;
